### ISSUE TITLE
Consider storing your program's output outside of GitHub

### ISSUE THREAD

**Issue by AskAlice** [mgerb/top-of-reddit#3]
I run into your repository more often than i'd like when I'm searching github for random bits of code centered around certain topics.
I can go through results, ctrl+f for your username, and get more than 1 result on every page.

ie https://github.com/search?utf8=%E2%9C%93&q=overwatch+udp+reverse&type=code&p=4

Yes I could filter out markdown files, but that would omit on-topic documentation

Alternately, consider aggregating your markdown or base64-encoding your word clouds inside the markdown with a [data uri](https://css-tricks.com/data-uris/), such that the file-size of your markdown files is larger than [350 KB](https://docs.github.com/en/search-github/github-code-search/about-github-code-search#limitations)

**Comment by mgerb** [comment]
I don’t have any plans to remove this content from GitHub’s search indexing. There may be a case where I would want it to show up in my search results.

If you don’t want to see this in your search results I suggest using the following query:

`overwatch udp reverse -repo:mgerb/top-of-reddit`
